# render posts with dates in the future
future: true

# minify html in production
minify_html: true

# create lunr index
create_index: true

# bust cache
bust_cache: true

# minify js
compress_js: true

# minify assets
sass:
  style: compressed
  load_paths: 
    - node_modules
